from typing import Any
from pydantic import BaseModel, ConfigDict, Field, field_validator


class PatientProfile(BaseModel):
    """Patient profile attributes relevant for personalized care planning."""

    model_config = ConfigDict(extra="ignore")

    age: int | None = Field(default=None, description="Patient age in years")
    allergies: str = Field(default="", description="Known patient allergies")
    food_likes: str = Field(default="", description="Foods the patient enjoys")
    food_dislikes: str = Field(default="", description="Foods the patient dislikes")
    dietary_restrictions: str = Field(default="", description="Dietary restrictions (e.g. low-sodium, diabetic, renal)")
    notes: str = Field(default="", description="Other medical or personal notes")


class CarePlan(BaseModel):
    """Structured Care Plan generated by Gemma 3.

    Designed to be concise, plain-language, and easy for older people to understand.
    Strictly grounded in the medical report without invented diagnosis or medications.
    """

    model_config = ConfigDict(extra="ignore")

    summary: str = Field(
        default="",
        description="A warm, concise, and plain-language summary of the report for an older adult.",
    )
    medicines: list[str] = Field(
        default_factory=list,
        description="List of prescribed medicines, dosages, and instructions explicitly stated in the report.",
    )
    what_to_do: list[str] = Field(
        default_factory=list,
        description="Clear, actionable daily steps recommended by the doctor.",
    )
    what_to_avoid: list[str] = Field(
        default_factory=list,
        description="Specific activities, foods, or behaviors the doctor advised against.",
    )
    food_guidance: list[str] = Field(
        default_factory=list,
        description="Dietary instructions aligned with doctor notes, cross-checked with allergies/restrictions.",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Safety warnings, potential allergy conflicts, or red-flag symptoms.",
    )
    follow_up: list[str] = Field(
        default_factory=list,
        description="Scheduled follow-ups, upcoming tests, or 'Needs verification' if unclear.",
    )
    doctor_questions: list[str] = Field(
        default_factory=list,
        description="Prepared questions for the patient or family to ask at their next doctor visit.",
    )
    conflicts: list[str] = Field(
        default_factory=list,
        description="Explicit conflicts detected between medical report and patient profile, requiring verification.",
    )
    sources: list[str] = Field(
        default_factory=list,
        description="Evidence excerpts or section references from the medical report.",
    )

    @field_validator(
        "medicines",
        "what_to_do",
        "what_to_avoid",
        "food_guidance",
        "warnings",
        "follow_up",
        "doctor_questions",
        "conflicts",
        "sources",
        mode="before",
    )
    @classmethod
    def ensure_list_of_strings(cls, v: Any) -> list[str]:
        if v is None:
            return []
        if isinstance(v, str):
            v = v.strip()
            return [v] if v else []
        if isinstance(v, (list, tuple)):
            return [str(item).strip() for item in v if item is not None and str(item).strip()]
        return [str(v)]

    def to_frontend_dict(self) -> dict[str, Any]:
        """Convert CarePlan to a dict containing both canonical keys and UI aliases."""
        data = self.model_dump()
        data["conflicts"] = list(self.conflicts)

        data["todo"] = list(self.what_to_do)
        data["avoid"] = list(self.what_to_avoid)
        data["food"] = list(self.food_guidance)
        data["followup"] = list(self.follow_up)
        data["questions"] = list(self.doctor_questions)

        data["resources"] = [
            {"title": src, "url": ""} if isinstance(src, str) else src
            for src in self.sources
        ]

        data["voice_text"] = self.summary

        return data
